version: "3.7"

services:
   app:
      build: .
      restart: unless-stopped
      container_name: project-service
      ports:
         - target:  8080
           published: 8080
      networks:
         - project-net
      working_dir: /app
      depends_on:
         - db

   db:
      image: mongo
      container_name: project-db
      volumes:
         - type: volume
           source: project-data
           target: /data/db
           volume:
             nocopy: true
      restart: unless-stopped
      ports:
         - target: 27017
           published: 27017
      networks:
         - project-net

networks:
   project-net:

volumes:
   project-data:
