@startuml
!pragma useVerticalIf on
floating note: CLIENT
Legend: Vx=view, Sx-n=service instance, Cx-n=client, Rk=resource id, Dk=resource data

start
:User enters Element; <<input>>
:User clicks SAVE; <<input>>
:POST CreateRequest(Vx, Rk, Dk); <<output>>
:show waiting state;
split
    :201 (Rk); <<output>>
    :Update client view (Dk);
split again
    :409 (Rk, SHADOW_DIFFERENT(shadow_data)); <<input>>
    :Show Content Decision Page;
    split
        :User clicks OVERWRITE; <<input>>
        :POST MergeRequest(Vx, Rk, MergeCmd::Client(Dk)); <<output>>
    split again
        :User clicks KEEP SERVER; <<input>>
        :POST MergeRequest(Vx, Rk, MergeCmd::Shadow(shadow_data)); <<output>>
    end split
    :show waiting state;
    split
        :200; <<input>>
        :Update client view (shadow_data);
    split again
        :4** or 500; <<input>>
        :Show Error Page;
        :User clicks OK; <<input>>
    end split
split again
    :409 (Rk, SHADOW_IDENTICAL(shadow_data)); <<input>>
    :Show Cancel Option;
    split
        :User clicks CANCEL; <<input>>
    split again
        :User clicks OK; <<input>>
        :POST MergeRequest(Vx, Rk, MergeCmd::Shadow(shadow_data)); <<output>>
        :show waiting state;
        split
        :200; <<input>>
        :Update client view (shadow_data);
        split again
            :other error; <<input>>
            :Show General Error Page;
            :User clicks OK; <<input>>
        end split
    end split
split again
    :409 (Rk, VIEW_PREEXISTING(resource_data)); <<input>>
    :Show View Pre-existing Page;
    :User clicks OK; <<input>>
split again
    :other error; <<input>>
    :Show General Error Page;
    :User clicks OK; <<input>>
end split
:Refresh client view;
stop
@enduml