@startuml
actor CA as "Client(A)"
actor CB as "Client(B)"
control SA1 as "Service(A)"
database DBA as "Database(A)"
control SB1 as "Service(B)"
database DBB as "Database(B)"
CA -> SA1: CreateRequest(R1, D1)
activate SA1
SA1 -> DBA: start tx for A
activate DBA
note over SA1, SB1
    Client B happens to concurrently send a CreateRequest for the same resource id R1 to Service(B).
    Note, Service(A) manages view A and Service(B) manages view B.
end note
CB -> SB1: CreateRequest(R1, D1)
note over SA1, SB1
    Service(B) happens to successfully process its request and issue a CreatedEvent for the same resource id first. 

    When Service(A) receives the CreatedEvent while it is still processing the CreateRequest 
    for its own view A, it must rollback its own transaction, return an error response to its Client(A)
    and not issue a CreatedEvent on its own.
end note
SA1 -> SA1: ... process CreateRequest(R1, D1)
activate SA1
SA1 -> DBA: insert Element(A, R1, D1) into Shadow and View
SA1 <- DBA: success


SA1 -> SB1: CreatedEvent(A, R1, D1)
activate SB1
SB1 -> DBB: start tx for B
activate DBB
SB1 -> SB1: ... process CreatedEvent(A, R1, D1)
activate SB1
SB1 -> DBB: insert Element(B, R1, D1) into Shadow 
@enduml