@startuml
!pragma useVerticalIf on
floating note: SERVICE
start
    :CreatedEvent(id, view_id, resource_data); <<input>>
    :Look up Shadow-Element by id; <<load>>
    if (element in shadow?) then (yes: Ignore, this is bus echo)
    else (no)
        :Create new Shadow-Element from resource_data; <<save>>
        if (view_id) then (own view) 
            :merge into view model;
        else (other view)
    end if
@enduml