@startuml
!pragma useVerticalIf on
floating note: CLIENT

start
:User enters Element; <<input>>
:User clicks SAVE; <<input>>
:POST CreateFunctionRequest(id, original_data); <<output>>
split
    :201 (id); <<output>>
    :update client view;
    stop
split again
    :409 (id, SHADOW_DIFFERENT(shadow_data)); <<input>>
    :Show Content Decision Page;
    split
        :User clicks OVERWRITE; <<input>>
        :POST MergeRequest(id, MergeCmd::Client(original_data)); <<output>>
    split again
        :User clicks KEEP SERVER; <<input>>
        :POST MergeRequest(id, MergeCmd::Shadow(shadow_data)); <<output>>
    end split
split again
    :409 (ID, SHADOW_IDENTICAL); <<input>>
    :Show Cancel Option;
    split
        :User clicks CANCEL; <<input>>
        stop
    split again
        :Use clicks OK; <<input>>
        :POST MergeRequest(id, MergeCmd::Shadow(shadow_data)); <<output>>
    end split
split again
    split 
        :409 (ID, VIEW_PREEXISTING); <<input>>
    split again
        :500<
    end split
    :Show Error Page;
    :User clicks OK; <<input>>
    stop
end split
split
    :200; <<input>>
    stop
split again
    split
        :500; <<input>>
    split again
        :422; <<input>>
    end split
    :Show Error Page
    :User Clicks OK; <<input>>
    stop
end split
@enduml