@startuml
'https://plantuml.com/activity-diagram-beta
floating note: SERVICE
Legend: Vx=view, Sx-n=service instance, Cx-n=client, Rk=resource id, Dk=resource data
start
split
    :POST CreateRequest(Vx, Rk, Dk); <<input>>
    :[[./endpoint-create-request.sdl.puml process create request]];
split again
    :POST MergeRequest(Vx, Rk, MergeCmd::Client(Dk)); <<input>>
    :Load Shadow-Element by Rk; <<load>>
    :Overwrite Shadow-Element with Dk;
    :Flag Shadow-Element as MODIFIED;
    :create View-Element from Dk;
    :link Shadow-Element and View-Element;
    :Save Shadow-Element and View-Element; <<save>>
    :publish ModifiedEvent(Vx, Rk, Dk); <<output>>
    :200 (Rk); <<output>>
split again
    :POST MergeRequest(Vx, Rk, MergeCmd::Shadow(Dk)); <<input>>
    :Load Shadow-Element by Rk; <<load>>
    if (Shadow-Element exists) then (loaded)
        if (Shadow-Element equals Dk) then (yes)
            :Create new View-Element from Shadow-Element;
            :Merge addtnl content from Dk;
            :link Shadow-Element and View-Element;
            :Save Shadow-Element and View-Element; <<save>>
            :200 (Rk); <<output>>
        else (no)
            :422 (Rk, SHADOW_HAS_BEEN_CHANGED); <<output>>
        endif
    else (Rk not found)
        :404 (Rk); <<output>>
    end if
end split
stop
@enduml
