@startuml endpoint CreateRequest
!pragma useVerticalIf on
floating note: SERVICE
legend right
Vx      : view, 
Sx-n    : service instance, 
Cx-n : client, 
Rk : resource id,
Dk : resource data
endlegend

start
    split
        :POST CreateRequest(Vx, Rk, Dk); <<input>>
        :Look up View-Element by Rk; <<load>>
        if (element in View) then (yes)
            :409 (Rk, VIEW_PREEXISTING); <<output>>
        else (no)
            :Look up Shadow-Element by Rk; <<load>>
            if (element in shadow) then (yes)
                if(Diff request vs shadow) then (identical)
                    :409 (Rk, SHADOW_IDENTICAL(shadow_data)); <<output>>
                else (different)
                    :409 (Rk, SHADOW_DIFFERENT(shadow_data)); <<output>>
                end if
            else (no)
                :create Shadow-Element(MODIFIED) from Dk;
                :create View-Element from Dk;
                :link Shadow-Element and View-Element;
                :Save Shadow-Element and View-Element; <<save>>
                :publish CreatedEvent(Vx, Rk, Dk); <<output>>
                :201 (Rk); <<output>>
            end if
        end if
    split again
        :... other events; <<input>>
        :... process other events; <<process>>
    end split
end
@enduml