@startuml
node dev_host {
	component Intellij
	component Browser {
		artifact process_ui_app <<Next app>>
	}
	component bash
	component Ansible
}

cloud linode {
	node process_server {
		node process_container <<docker>> {
			interface process <<REST>>
			component fscl-process-service
			process -- fscl-process-service
		}
	}
	node process_db {
		node process_db_container <<docker>> {
			component debezium
			component postgres
			postgres --> debezium
		}
	}
	node process_ui_server {
		node process_ui_container <<docker>> {
			component fscl-process-ui <<Next server>>
		}
	}
	node bus_server {
		node bus_container <<docker>> {
			component kafka
		}
	}
	
	node automation_server {
		node automation_container <<docker>> {
			component fscl-automation-service
		}
	}
}

process_ui_app --> fscl-process-ui
fscl-process-ui --> process: https
bash --> automation_service: ssh
process_ui_app --> process: https
fscl-process-service -- kafka: tcp
debezium -- kafka: tcp
fscl-process-service -- postgres: tcp
automatifscl-automation-serviceon_service -- kafka: tcp
@enduml