@startuml
component fscl_core_lib <<library>>
component fscl_ui_core <<library>>
component fscl_automation_service <<microservice>>
interface "fscl/automation" as automation <<REST API>>
component fscl_automation_ui <<web client>>
component automation_db <<RDBMS>>

interface "fscl/safety" as safety <<REST API>>
component fscl_safety_service <<microservice>>
component fscl_safety_ui <<web client>>
component safety_db <<RDBMS>>

interface "fscl/process" as process <<REST API>>
component fscl_process_service <<microservice>>
component fscl_process_ui <<web client>>
component process_db <<RDBMS>>

component event_bus <<kafka-broker>>

fscl_process_ui --> process
fscl_process_ui --> fscl_ui_core
process --- fscl_process_service
fscl_process_service --> fscl_core_lib
fscl_process_service --> process_db
fscl_process_service --> event_bus

fscl_automation_ui --> automation
fscl_automation_ui --> fscl_ui_core
automation --- fscl_automation_service
fscl_automation_service --> fscl_core_lib
fscl_automation_service --> automation_db
fscl_automation_service --> event_bus

fscl_safety_ui --> safety
fscl_safety_ui --> fscl_ui_core
safety --- fscl_safety_service
fscl_safety_service --> fscl_core_lib
fscl_safety_service --> safety_db
fscl_safety_service --> event_bus
@enduml
